AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Serverless AI Maintenance Agent infrastructure

Resources:
  PropertyImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub property-images-ai-agent-${AWS::AccountId}-${AWS::Region}
      Tags:
        - Key: Project
          Value: Agentic-Prop
        - Key: Owner
          Value: Mpho
        - Key: Environment
          Value: Dev

Outputs:
  BucketName:
    Description: Name of the S3 bucket for storing property images
    Value: !Ref PropertyImagesBucket

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt PropertyImagesBucket.Arn

  Region:
    Description: AWS region where the stack is deployed
    Value: !Ref AWS::Region

      
